version: '3'
services:
  api:
    image: sample-auth-app
    # restart: always
    build: .
    networks:
      - backend
    ports:
      - '4001:4001'
    depends_on:
      - mongo

  mongo:
    image: mongo
    # # restart: always
    # container_name: mongodb
    # volumes:
    #   - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth #--smallfiles

  # web-cli:
  #   image: sample-auth-app
  #   networks:
  #     - backend
  #   command: sh

networks:
  backend:
    driver: bridge